### ISSUE TITLE
Text after the pipe

### ISSUE THREAD

**Issue by DutchPete** [bicarlsen/obsidian_image_caption#1]
Thanks for a useful plug-in, which works as described.

I also use a snippet, designed by Lithou, which allows you to place an image in various position relative to the text. An example format: `![[image.png|+side -med]]`. So, guess what …… your plug-in sees that as a caption. The image does get arranged as per the snippet, but +side and -med get placed as a caption under the image in Preview.

I want to be able to use thesnippet AND you plug-in without getting funny captions. Lithou proposes [a solution](https://forum.obsidian.md/t/how-to-achieve-css-code-snippets/8474/196?u=klaas).

Could you have a look at that and see what is possible?
I have attached Lithou's snippet.
[pub-Image_Flags.css.zip](https://github.com/bicarlsen/obsidian_image_caption/files/7465533/pub-Image_Flags.css.zip)

**Comment by bicarlsen** [comment]
Great suggestion. I decided to add a **Delimeter** setting to make this feature a bit more robust. It is avaialble in Release 0.0.7.

**Comment by DutchPete** [comment]
I just installed version 0.0.7 (I love that number !), and this is how I formatted an image:

`![[image.png|+side -lg “My caption”]]`, but in Preview it literally shows `+side -lg “My caption”` below the image. Note: the snippet's `+side -lg` flag does still work, but it is also taken as part of the caption.

I also tried `![[image.png|“My caption” +side -lg “My caption”]]`, but in Preview it shows `“My caption” +side -lg “My caption”` below the image.

Please advise.

**Comment by bicarlsen** [comment]
Did you set `"` as the delimeter in the settings?

**Comment by DutchPete** [comment]
No, I had not. Now it works!

Couple of suggestions:

* in the README it is worth pointing out that the delimiter character **has to be set**.
* You state “A single delimeter can be used”, but even if in the Settings one puts only e.g. `!`, the caption text still has to have a `!` on either side, like so: `![[image.png|!my caption!]]`. With only this `![[image.png|!my caption]], i.e. with only 1 `!`, the caption text will not be rendered under the image in Preview. IMO it is worth pointing that out in the README.

**Comment by bicarlsen** [comment]
Than you for the input. I tried to clariy it in the README with the latest commit.
