### ISSUE TITLE
Doesn't work for images in lists

### ISSUE THREAD

**Issue by firinael** [bicarlsen/obsidian_image_caption#13]
Pretty straightforward. Adding a caption to an image in a list just makes the caption show up as the next bullet point.

![image](https://user-images.githubusercontent.com/67032657/160900332-3748523c-2a74-4b1a-b9fa-51fa453c9855.png)

to

![image](https://user-images.githubusercontent.com/67032657/160900377-1da120bd-ca31-4fe8-892c-24da09f6ca0a.png)

**Comment by bicarlsen** [comment]
It seems to be working for me. First please make sure everything is up to date. If that doesn't fix the issue perhaps you can elaborate on your setup and the source markdown, or try to figure out what is causing it not to work. 
![Screenshot from 2022-03-31 12-53-52](https://user-images.githubusercontent.com/4098092/161039632-f782e1c7-640a-43b0-bb03-0d2ba13e1dc5.png).

**Comment by bicarlsen** [comment]
I'll close this issue due to lack of activity. If you experience another problem please feel free to open another issue.
