### ISSUE TITLE
Maintain aspect ratio when resizing image

### ISSUE THREAD

**Issue by andrei-micuda** [bicarlsen/obsidian_image_caption#14]
Maybe we could have something like:

```
![[my_amazing_image.png|50 "Amazing Caption"]]
```

Meaning if we only specify one dimension for resizing (let's say by convention it would be the width), the height should automatically be adjusted to maintain the original ratio of the image.

**Comment by bicarlsen** [comment]
Great suggestions, thank you. This should be working in [version 0.0.13](https://github.com/bicarlsen/obsidian_image_caption/releases/tag/0.0.13). Give it a try and let me know.

You can use the keyword `auto` to allow auto-scaling along one of the directions. See the **Rescaling** section of the [README](https://github.com/bicarlsen/obsidian_image_caption#use) for details.

**Comment by andrei-micuda** [comment]
Awesome, I just updated the plugin and it works like a charm.
Thanks for the quick response and implementation!

Keep up the good work!
