### ISSUE TITLE
Doesn't seem to work in the newest Obsidian version

### ISSUE THREAD

**Issue by Panossa** [bicarlsen/obsidian_image_caption#15]
Hey, I'm a fairly new user to Obsidian so maybe I did something wrong, however I can't get the captions to work at all.
None of your code examples from the readme work, even in the sandbox vault. :/

**Comment by bicarlsen** [comment]
I just tested on Obsidian v 0.14.6 and it seems to be working for me. The first thing to check is that there are no conflicts between plugins. To do this you can turn off all the plugins, and turn each on individually to check if they work alone. Then start turning them on one-by-one to see if something breaks.

If this does not provide information you can check if there is an error ocurring. You can do this by opening the developer panel (https://forum.obsidian.md/t/how-to-access-the-console/16703) and checking the `Console` tab for errors.

It would also be useful if you provide a minimal example of the markdown which is not working along with a screenshot of the result.

**Comment by bicarlsen** [comment]
I'll close this issue due to lack of activity. If you experience any other issues, please feel free to open another issue.
