### ISSUE TITLE
Centering caption

### ISSUE THREAD

**Issue by Leo-Zarni01** [bicarlsen/obsidian_image_caption#18]
Hi, I'm a beginner here. How do you center the caption because I've already centered the image but I need to include css styling for the plugin to make changes but I'm not sure how to. 

![image](https://user-images.githubusercontent.com/50450659/174331487-cc1ff920-294a-46a7-8c88-342ac25f88bf.png)

**Comment by bicarlsen** [comment]
Check out Issue #5 to see if that resolves your issue. If not, please provide me with some more details about your setup.

**Comment by Leo-Zarni01** [comment]
Hi, so the centering works now! Just one more, how do I add a few space between the image and the caption just to give some breathing space since they seem so tight together.

**Comment by bicarlsen** [comment]
I suggest looking into the CSS `margin` and `padding` properties for this.

**Comment by Leo-Zarni01** [comment]
Thank you! I have resolved this issue now. Again, thanks for the speedy response!
