### ISSUE TITLE
Can't find suitable version

### ISSUE THREAD

**Issue by amilosevic-grid** [bicarlsen/obsidian_image_caption#2]
When trying to install through Obsidian, it throws an error:
No appropriate version found.

**Comment by bicarlsen** [comment]
So sorry about that. I'm not sure what is causing the error at the moment, so [posted in the developers forum](https://forum.obsidian.md/t/no-appropriate-version-found-error-when-installing-plugin/26622) for some assistance. For now you can manually install the plugin by cloning the repositiory into your `.obsidian/plugins` folder or downloading the `main.js` and `manifest.json` into the `.obsidian/plugins/image_caption` folder inside your vault.

For some more help you can check out the [Obsidian Sample Plugin](https://forum.obsidian.md/t/no-appropriate-version-found-error-when-installing-plugin/26622), and I will post here once I resolve the issue.

**Comment by bicarlsen** [comment]
@amilosevic-grid Can you check which version of obsidian you are running. I just verified that the installation works with Obsidian 0.12.19, which is the minimum required version for the plugin to work, and the current version of Obsidian.

**Comment by amilosevic-grid** [comment]
aah didn't update my Obsidian. Sorry, my bad 😄 
btw, the plugin looks great, nice work!

**Comment by bicarlsen** [comment]
Ah great :)

Thank you very much. And if you run into any issues in the future or have any suggestion, please let me know.
