### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by th1nkful** [bicarlsen/obsidian_image_caption#4]
When Obsidian on mobile loads, the plugin always fails to load but works fine on desktop. 

Anything I can do to help debug?

**Comment by bicarlsen** [comment]
Thanks for pointing this out. If you are familiar with debugging on your mobile device, it would be very useful if you could send me the error message.

**Comment by AndyLiu9** [comment]
Thanks for making the plugin. On my iPhone, I just fail to load the plugin so maybe we can't really test it on mobile devices. Or the error message is simply "Failed to load plugin".

**Comment by th1nkful** [comment]
![96D77AEA-8557-4B90-9A5E-CEAC13BA5ECE](https://user-images.githubusercontent.com/9315568/142728968-89329028-a044-4557-8d86-b45e6f20a99f.jpeg)

this is the error in console when trying to enable the plugin

**Comment by th1nkful** [comment]
Tried adding extra console.logs and syntax errors to the top of the main.js in the plugin - still shows as the same error

**Comment by lishid** [comment]
This is due to the use of the lookbehind regex which is not supported on any Safari based devices (iOS).

https://github.com/bicarlsen/obsidian_image_caption/blob/7b1f02e9a7323d517777f34da6935817a8c60f9a/src/main.ts#L88

**Comment by th1nkful** [comment]
@lishid how’d you figure that out? Come across a similar issue before? Super awesome to have spotted that was causing it

**Comment by lishid** [comment]
Unfortunately, I am the only one who can run a remote debugger to the iOS app because Apple only allows remote debugging on a debug version of the app, and debug versions aren't allowed to be released on the App Store or TestFlight.

Using the remote debugger on Safari allowed me to view the error in details.

**Comment by th1nkful** [comment]
Thanks @lishid, I thought the name looked familiar but didn’t click that you were an Obsidian dev! Thanks for taking the time to check 

@bicarlsen can you add any context around what issue you were trying to fix with the regex? I can tell you’re adjusting the styling but I don’t follow the why/what to make sure a PR maintains the intended functionality

**Comment by lishid** [comment]
One way to write the regex is matching all chars except `\\` and replacing it ($1) back.

```js
/(^|[^\\])#/
```

**Comment by th1nkful** [comment]
Changed the code inside .obsidian to use this and the plugin both loads and works on mobile. @bicarlsen happy to accept a MR that changes the regex to the above to support mobile?

**Comment by bicarlsen** [comment]
Updated the regex in [release 0.0.8](https://github.com/bicarlsen/obsidian_image_caption/releases/tag/0.0.8) and it appears everything is working :).

Thank you for your help @lishid  and @th1nkful .
