### ISSUE TITLE
Caption centering

### ISSUE THREAD

**Issue by Alekssavin** [bicarlsen/obsidian_image_caption#5]
Hi.
It looks like there is there is no option to align the caption with the image itself. The caption starts in the beginning of the new line.
![image](https://user-images.githubusercontent.com/56745247/142942823-82e54db0-88e0-48a1-af8e-0a63e50be380.png)

**Comment by bicarlsen** [comment]
Thank you for the suggestion.

How are you aligning the image? Do you have a suggestion about the best way to allow for caption alignment? Should it be a global setting? Sould it be an option you include with the caption so it only applies locally?

You can use the custom CSS setting for alignment, but that would apply globally, which I guess isn't what you want.

**Comment by siphyshu** [comment]
Hey @bicarlsen, How would you apply the custom CSS for center alignment globally?

**Comment by bicarlsen** [comment]
Add `text-align: center;` to **Settings > Image Caption > CSS**. You can place any CSS style you want there.

**Comment by Alekssavin** [comment]
That's what I wanted, thank you.
Images are not centered together with the caption automatically, so I guess I'll have to center them with CSS snippets applied to Obsidian.

**Comment by bicarlsen** [comment]
Great :) 

If you have any suggestions on how to better implement alignment, I'm certainly open to the feedback.
