### ISSUE TITLE
Cannot set image size, and use this plugin at the same time.

### ISSUE THREAD

**Issue by Hunanbean** [bicarlsen/obsidian_image_caption#8]
Have tried with delimiters "  {}  !!, etc

![[picture.png]] works at default size
![[picture.png|200x200]] works and sets the image to 200x200 pixels
![[picture.png|"Caption Phrase"]]  works, of course while " is delimiter.
![[picture.png|200x200 "Caption Phrase"]] does not work completely. Caption Phrase works as the caption, but the size is ignored.

I have found no combination that wil allow size and caption to work together.

Thank you

**Comment by bicarlsen** [comment]
Thank you for pointing that out.

This should be fixed in release `0.0.10`. I've updated the `README` to reflect the fix. Give it a try and let me know if it's working for you.

**Comment by Hunanbean** [comment]
Thank you very much. It is working now. I wonder if you are familiar with "Ozan's Image in Editor Plugin" It has several features, one of which it that it displays the image while in editor mode. I just wanted to note that without your plugin, Ozan's does change the display size in the editor too. Unfortunately, while using both plugins together, the 'signal' is not getting from "Image Caption" to Ozan's. 

Thanks again, and be well

**Comment by bicarlsen** [comment]
Glad it's working.

I'm not aware of it, but I'll take a look and see if we cna get them integrated.
