### ISSUE TITLE
How do have the caption appear UNDER the image?

### ISSUE THREAD

**Issue by ReaderGuy42** [bicarlsen/obsidian_image_caption#9]
Like your plugin! However, the captions appear to the right of  the image, how do I set it so it's underneath?

Thanks :)

**Comment by bicarlsen** [comment]
Usually captions do appear under the image. Can you share an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) as well as which platform you are having issues on (Windows, Mac, Linux, mobile).

If you know how to open the developer tools, you can investigate the HTML and CSS to see what is going on. If you find anything please send it to me.

If not, there may be another plugin causing issues. Try turning off all the plugins except Image Caption, and turning them on one by one to see which one is causing the issue.

**Comment by ReaderGuy42** [comment]
Sorry, I noticed the issue was with a snippet to create a grid of images, so you could have images next to each other, and this is not working well for me: https://github.com/zremboldt/obsidian-media-grid
Once I got rid of that the captions were centered again. Thanks though!
